#define BIT8_SNGL_PRES_CHECKSUM 0
#define BIT8_DBL_PRES_CHECKSUM 1
#define BIT8_SNGL_PRES_RES_CHECKSUM 2
#define BIT8_HONEYWELL_CHECKSUM 3
#define BIT8_CRC 4

#define CORR_SNGL_BIT 0
#define CORR_BURST 1
#define CORR_RAND 2
#define CORR_NONE 3