#define BIT8_SNGL_PRES_CHECKSUM 0
#define BIT8_DBL_PRES_CHECKSUM 1
#define BIT8_SNGL_PRES_RES_CHECKSUM 2
#define BIT8_HONEYWELL_CHECKSUM 3
#define BIT8_CRC 4
#define BIT8_HC_SEC 5
#define BIT8_HC_SECDED 6
#define BIT8_RESID_ARITH 7
#define BIT8_BIRESID 8
#define BIT32_SNGL_PRES_CHECKSUM 9
#define BIT32_DBL_PRES_CHECKSUM 10
#define BIT32_SNGL_PRES_RES_CHECKSUM 11
#define BIT32_HONEYWELL_CHECKSUM 12
#define BIT32_CRC 13
#define BIT32_HC_SEC 14
#define BIT32_HC_SECDED 15
#define BIT32_RESID_ARITH 16
#define BIT32_BIRESID 17

#define CORR_SNGL_BIT 0
#define CORR_BURST 1
#define CORR_RAND 2
#define CORR_NONE 3

#define DEFAULT_ITERATIONS 100

#define BUFF_SIZE 100

#define BITS_PER_BYTE  8
#define BYTES_PER_CHAR 1
#define NUM_CHAR       1
#define SIZE_DW_BITS (BITS_PER_BYTE*BYTES_PER_CHAR*NUM_CHAR)
#define MAX_DW_VALUE (1 << SIZE_DW_BITS)-1